services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=resumedb
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resumedb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
